### ISSUE TITLE
Configure the code deployment pipeline

### ISSUE THREAD

**Issue by nikdragovic** [emory-libraries/dlp-lux#18]
## Story
As a Software/DevOps Developer, I want to configure the code deployment pipeline, so that I can enable the team to co-develop the application using GitHub and hosted environments.

## Acceptance Criteria
- [x] All team members verify that they can deploy the code.
- [x] Environments include arch, test, and prod.
- [x] All team members verify that all environments can be viewed on campus or using the VPN.
- [x] All team members have AWS accounts and Emory Sponsored Accounts, as needed.

##Notes
Collin says this should be easy to implement, as it is currently in place for Curate.
