### ISSUE TITLE
Implement "Emory High Download” Access Category

### ISSUE THREAD

**Issue by nikdragovic** [emory-libraries/dlp-lux#251]
## User Story
As a collection manager, I want only the Emory community (logged in to Lux) to be able to view/play, download, share full quality files for selected digital objects, so that I can support Emory’s teaching and research mission while respecting rights and agreements.

## Image resolution notes
The highest quality version available for the preferred file delivered in the Viewer. 

## Acceptance Criteria
Given
I am an Emory Collection Manager
When
I deposit material with rights restrictions and select the Emory High Download visibility option in Curate
Then
I can deliver a high quality content file through Lux to any Emory-authenticated user who wants to view, download, or share it with others; and I can see and manage the preservation files in Curate

Given
I am an Emory-affiliated content consumer logged into the Lux product
When
I discover an object through the Lux product 
Then
I am able to see a high quality file in the Lux viewer and I can download and share it with others

Given
I am a content consumer not logged into the Lux product
When
I follow a shared a link to a Cor repository object 
Then
I am not able to see a high quality file in Lux or load it into another IIIF viewer and I am also not able to download or share it with others
Ranked scenarios for non-logged in user:
- [x] User sees a page noting that login is required to see show page and object
- [ ] User sees show page and metadata but no files

## Sample objects
* https://curate-arch.library.emory.edu/concern/curate_generic_works/740ksn02z0-cor?locale=en
* https://curate-arch.library.emory.edu/concern/curate_generic_works/1439zw3r4z-cor?locale=en
* https://curate-arch.library.emory.edu/concern/curate_generic_works/7784j0zpg1-cor?locale=en

## Additional Information
[DCE’s Access Controls table
](https://docs.google.com/spreadsheets/d/1JGND3IjTK0kvqkKKX0Wi0dHxtcYRZD1QQM-BqJjfrBg/edit#gid=1226450121)
[Emory Ticket Notes
](https://docs.google.com/document/d/1Z68oz1PFWHBOPNRNJpyYKUi5MK8R87DYtP2oJzJYJTg/edit?usp=sharing)

**Comment by maxkadel** [comment]
Currently search results show all Works and Collections, but if user is 
not logged in, restricted items go to 404 page, not show page.

Further work is needed to have search results reflect user's authorization

Logged in
![image](https://user-images.githubusercontent.com/45948126/73217617-432ff300-4126-11ea-9c0a-83cb85616f03.png)

Same page, not logged in
![image](https://user-images.githubusercontent.com/45948126/73217654-52af3c00-4126-11ea-9c31-7f8e737e6a2a.png)

**Comment by maxkadel** [comment]
Bess and Max are not clear what an unauthenticated user's experience should be. 

What should an unauthenticated user see? 
 - [ ] Low resolution file 
 - [ ] Only metadata 
 - [ ] Message that they must authenticate to access information

**Comment by maxkadel** [comment]
Carved out #261 from this issue

**Comment by maxkadel** [comment]
Sample object is not an "Emory High Download" object, it is a Repository manager only object. Cannot find an Emory High Download object with manifest in any of the Curate environments.

**Comment by maxkadel** [comment]
- [ ] Search results show object, whether or not user is logged in
 - [ ] Logged in user can view "show" page
 - [ ] Logged in user can share or download object using UV
 - [ ] An unauthenticated user cannot open the show page, and gets routed to a custom 404 page
 - [ ] An unauthenticated user cannot download or share the image (via Lux), because they cannot open the show page

**Comment by eporter23** [comment]
@maxkadel I set 3 works in curate-arch to use this visibility setting but I assume they are pending the SOLR synch. let me know if you need more samples.

**Comment by eporter23** [comment]
Added a few more including a yearbook and a yellowback volume
