### ISSUE TITLE
Simple Object Show Page

### ISSUE THREAD

**Issue by nikdragovic** [emory-libraries/dlp-lux#37]
## Story
As a Repository Administrator, I want to display a test simple image object view page, so that I can examine the page with minimal configuration to determine what additional work is needed for beta.

#### Checklist
- [ ] Universal Viewer appears on the page
- [ ] Image appears in Universal Viewer
- [ ] Desired metadata fields display with proper labels

#### Links to Additional Information
Test objects: (https://docs.google.com/spreadsheets/d/1LAElld_SWTZ72A2QtK1N7JNOwiG9cHgK_ck19mlRgLQ/edit?usp=sharing)

**Comment by nikdragovic** [comment]
Depending on scope discussion, this may convert to a sprint goal, with components of the page as epics.
