### ISSUE TITLE
Implement Universal Viewer

### ISSUE THREAD

**Issue by nikdragovic** [emory-libraries/dlp-lux#38]
## Story
As an end user, I want to use the Universal Viewer on the work show page, so that I can interact with the content directly in the digital library interface.

## Acceptance criteria
- [ ] Test images load within five seconds upon first viewing.
- [ ] Images are cached after first viewing for loading within two seconds upon subsequent viewings.
- [ ] Images are delivered via Cantaloupe server.
