### ISSUE TITLE
Configure Shibboleth for Lux (Blacklight)

### ISSUE THREAD

**Issue by tmiles2** [emory-libraries/dlp-lux#6]
## Acceptance Criteria
- [x] Clicking "Login" button in Blacklight header leads to Shibboleth authentication page
- [x] Succeeds in authenticating with Nik's login credentials
- [ ] User returns to prior location in Lux after authentication - de-scoped 
- [x] "Login" button switches to user's name after login

## To Discuss
Confirm initial scope: that this will later be the authentication for access controls, and that testing for access restrictions will be affiliated with Access Restrictions work.
